<?php
$title = 'Profile';
$this->headTitle($title);
?>
<?php
if(isset($data) && !empty($data)) :
?>
<h3><?= $data->firstName . '&nbsp;' . $data->lastName .'\'s&nbsp;';?><?= $this->escapeHtml($title); ?></h3>
<p>
	<?= $this->flashMessenger()->render('info'); ?>
	<?php
	if($this->acl->isAllowed($this->user, $data, 'edit')) {
	?>
    <a class="btn btn-primary" href="<?= $this->url('profile', ['action' => 'edit-profile', 'userName' => $data->userName]) ?>" role="button">Edit Profile</a>
	<?php 
	}
	?>
</p>
<div class="container">
  <div class="row">
    <div class="col">
      Column
    </div>
    <div class="col">
      Column
    </div>
    <div class="col">
      Column
    </div>
  </div>
</div>
<?php
else :
?>
<?= $this->translate('missing_profile_data'); ?>
<?php
endif;
?>