<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Aurora MVC Content Management System</h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="http://webinertia.net/aurora" target="_blank">Aurora CMS</a>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on Aurora CMS.
    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://github.com/Tyrsson/Aurora-Laminas" target="_blank">
        Check Aurora on GitHub &raquo;
    </a>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Follow Development</h2>
        <div class="card-body">
            <p>
                Aurora CMS is a private project that is being actively developed by
                Webinertia Data Systems LLC. 
            </p>

            <a class="btn btn-primary" href="http://webinertia.net/aurora/portal" target="_blank">Aurora Project Portal &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Discover Modules</h2>
        <div class="card-body">
            <p>
                Aurora CMS is a modular application.
                Aurora ships with base functionality to handle nearly everything you may need to do
                on the average website. If by chance the functionality is not in the default build our
                development team can handle any use case. Feel free to contact us!!!
            </p>

            <a class="btn btn-primary" href="http://webinertia.net/aurora/modules" target="_blank">
                Aurora Modules &raquo;
            </a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Help &amp; Support</h2>
        <div class="card-body">
            <p>
                If you need any help or support while developing with Aurora,
                you may reach us via email @ support@webinertia.net
            </p>
        </div>
    </div>
</div>
